CREATE TABLE FORUM_POLLS_OPTIONS (
    ID NUMBER,
    CONSTRAINT OPTION_PK PRIMARY KEY (ID),
    ID_POST NUMBER,
    CONSTRAINT POST_FK FOREIGN KEY(ID_POST) REFERENCES FORUM_POSTS (ID),
    ID_USER NUMBER,
    TITLE NVARCHAR2(64),
    DATE_POST DATE
);