CREATE TABLE FORUM_POSTS (
    ID NUMBER,
    CONSTRAINT POSTS_PK PRIMARY KEY (ID),
    ID_SUBCATEGORIE NUMBER,
    CONSTRAINT SUBCATEGORIE_FK FOREIGN KEY(ID_SUBCATEGORIE) REFERENCES FORUM_SUBCATEGORIES (ID),
    ID_USER NUMBER,
    CONSTRAINT USER_FK FOREIGN KEY(ID_USER) REFERENCES USERS (ID),
    PARENT_POST NUMBER,
    TITLE NVARCHAR2(90),
    CONTENT CLOB,
    IS_POOL CHAR,
    DATE_POST DATE,
    IP NVARCHAR2(20)
);