CREATE TABLE FORUM_POLLS_OPTIONS_VOTES (
    ID NUMBER,
    CONSTRAINT VOTES_PK PRIMARY KEY (ID),
    ID_POLL_OPTION NUMBER,
    CONSTRAINT POLL_OPTION_FK FOREIGN KEY(ID_POLL_OPTION) REFERENCES FORUM_POLLS_OPTIONS (ID),
    ID_USER NUMBER,
    CONSTRAINT USER_VOTES_FK FOREIGN KEY(ID_USER) REFERENCES USERS (ID),
    DATE_POST DATE,
    IP NVARCHAR2(20)
    );