CREATE TABLE FORUM_SUBCATEGORIES (
    ID NUMBER,
    CONSTRAINT SUBCATEGORIES_PK PRIMARY KEY (ID),
    ID_CATEGORIES NUMBER,
    CONSTRAINT CATEGORIES_FK FOREIGN KEY(ID_CATEGORIES) REFERENCES FORUM_CATEGORIES (ID),
    TITLE NVARCHAR2(45),
    DESCRIPTION CLOB,
    DATE_SUBCATEGORIES DATE,
    IP NVARCHAR2(20)
);