CREATE TABLE CUSTOMERS (
CUSTOMER_ID NUMBER,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
COMPANY_NAME NVARCHAR2(30),
CONTACT_NAME NVARCHAR2(30),
CONTACT_TITLE NVARCHAR2(30),
ADDRESS NVARCHAR2(30),
CITY NVARCHAR2(30),
REGION NVARCHAR2(30),
POSTAL_CODE NVARCHAR2(30),
COUNTRY NVARCHAR2(30),
PHONE NUMBER,
FAX NUMBER
);