 CREATE TABLE SUPPLIERS (
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIER_PK PRIMARY KEY (SUPPLIER_ID),
COMPANY_NAME NVARCHAR2(30),
CONTACT_NAME NVARCHAR2(30),
CONTACT_TITLE NVARCHAR2(30),
ADDRESS NVARCHAR2(30),
CYTI NVARCHAR2(30),
REGION NVARCHAR2(30),
POSTAL_CODE NVARCHAR2(30),
COUNTRY NVARCHAR2(30),
PHONE NUMBER,
FAX NUMBER,
HOME_PAGE NVARCHAR2(30)
);