CREATE TABLE ORDERS (
    ID NUMBER CHECK (ID < 10000),
    CONSTRAINT ORDER_PK PRIMARY KEY(ID),
    USER_ID NUMBER UNIQUE,
    ROOM_ID NUMBER UNIQUE,
    DATE_FROM DATE,
    DATE_TO DATE,
    MONEY_PAID  FLOAT(2)
);